
tone: "amigable"
constraints:
  no_out_of_stock: true
  max_items_per_message: 20
preferences:
  preferred_brands: ["Acme", "La Serenísima"]
  inclusive_language: true
  units_default: "unidad"
parsing:
  quantity_words:
    uno: 1
    una: 1
    dos: 2
    tres: 3
    media: 0.5
